<?php
/**
 * @file
 * Contact reference field module file.
 */

 include_once 'hid2_contact_ref.features.inc';

/**
 * Implements hook_field_info().
 */
function hid2_contact_ref_field_info() {
  return array(
    'hid2_contact_ref' => array(
      'label' => t('Contact reference'),
      'description' => t('This field stores the ID of a HID contact.'),
      'settings' => array('options_list_limit' => NULL),
      'instance_settings' => array(),
      'default_widget' => 'hid2_contact_ref',
      'default_formatter' => 'hid2_contact_ref_full',
    ),
  );
}

/**
 * Implements hook_field_validate().
 */
function hid2_contact_ref_field_validate($entity_type, $entity, $field, $instance, $langcode, $items, &$errors) {
  // Check if the contact exists in HID.
  foreach ($items as $delta => $item) {
    if (is_array($item) && !empty($item['user_id'])) {
      if (!$contact = hid2_contact_ref_get_contact($item['user_id'])) {
        $errors[$field['field_name']][$langcode][$delta][] = array(
          'error' => 'invalid_contact_id',
          'message' => t(
            '%name: you have specified an invalid contact id for this reference field.',
            array('%name' => $instance['label'])
          ),
        );
      }
    }
  }
}

/**
 * Implements hook_field_is_empty().
 */
function hid2_contact_ref_field_is_empty($item, $field) {
  return empty($item['user_id']);
}

/**
 * Implements hook_field_widget_info().
 */
function hid2_contact_ref_field_widget_info() {
  $return = array();

  $return['hid2_contact_ref_autocomplete'] = array(
    'label' => t('HID contact reference autocomplete'),
    'field types' => array('hid2_contact_ref'),
    'settings' => array(),
    'behaviors' => array(
      'multiple values' => FIELD_BEHAVIOR_DEFAULT,
      'default value' => FIELD_BEHAVIOR_DEFAULT,
    ),
  );

  return $return;
}

/**
 * Implements hook_field_widget_form().
 */
function hid2_contact_ref_field_widget_form(&$form, &$form_state, $field, $instance, $langcode, $items, $delta, $element) {
  $default_value = '';
  if (!empty($items[$delta])) {
    if ($contact = hid2_contact_ref_get_contact($items[$delta]['user_id'])) {
      $label = $contact->name;
      $default_value = "$label [id: $contact->_id]";
    }
  }

  $element += array(
    '#type' => 'textfield',
    '#title' => t('Contact'),
    '#autocomplete_path' => 'hid2/autocomplete/all',
    '#default_value' => $default_value,
    '#required' => $element['#required'],
  );

  $element['#element_validate'][] = 'hid2_contact_ref_field_widget_validate';

  return array('user_id' => $element);
}

/**
 * Validation callback to be able to translate the id.
 */
function hid2_contact_ref_field_widget_validate($element, &$form_state) {
  $value = $element['#value'];
  if (!empty($value)) {
    if (preg_match('/\[id: (.+)\]/', $value, $matches)) {
      form_set_value($element, $matches[1], $form_state);
    }

  }
}

/**
 * Implements hook_field_formatter_info().
 */
function hid2_contact_ref_field_formatter_info() {
  $return = array();

  $return['hid2_contact_ref_full'] = array(
    'label' => t('Hid contact reference formatter'),
    'field types' => array('hid2_contact_ref'),

  );

  return $return;
}

/**
 * Implements hook_ield_formatter_settings_summary().
 */
function hid2_contact_ref_field_formatter_settings_summary($field, $instance, $view_mode) {
  return t('HID contact reference field');
}

/**
 * Implements hook_field_formatter_view().
 */
function hid2_contact_ref_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, &$items, $display) {
  $element = array();
  switch ($display['type']) {
    case 'hid2_contact_ref_full':
      $wrapper = entity_metadata_wrapper($entity_type, $entity);
      foreach ($items as $delta => $item) {
        if ($contact = hid2_contact_ref_get_contact($item['user_id'])) {
          $element[$delta] = array(
            '#theme' => 'hid2_contact_ref_single_contact',
            '#contact' => $contact,
            '#cache' => array(
              'keys' => array('hid_contact', $entity_type, $wrapper->getIdentifier(), $item['user_id']),
              'bin' => 'cache',
              'expire' => time() + 3600,
              'granularity' => DRUPAL_CACHE_PER_PAGE,
            ),
          );
        }
      }
      break;

  }
  return $element;
}

/**
 * Implements hook_field_update().
 */
function hid2_contact_ref_field_update($entity_type, $entity, $field, $instance, $langcode, &$items) {
  // Clear the render cache for the contact field.
  if ($field['type'] == 'hid2_contact_ref') {
    $wrapper = entity_metadata_wrapper($entity_type, $entity);
    cache_clear_all('hid_contact:' . $entity_type . ':' . $wrapper->getIdentifier() . ':', 'cache', TRUE);
  }
}

/**
 * Implements hook_menu().
 */
function hid2_contact_ref_menu() {
  $items = array();

  $items['admin/config/services/hid2_contact_ref'] = array(
    'title' => 'Humanitarian ID Contact Reference',
    'description' => 'Configure the API endpoint, key, and secret for the Humanitarian ID Contact Reference',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('hid2_contact_ref_settings_form'),
    'access arguments' => array('administer site configuration'),
    'file' => 'hid2_contact_ref.pages.inc',
  );

  $items['hid2/autocomplete'] = array(
    'page callback' => 'hid2_contact_ref_autocomplete_callback',
    'access arguments' => array('access content'),
  );

  return $items;
}

/**
 * Callback function for autocomplete.
 */
function hid2_contact_ref_autocomplete_callback($type, $string = '') {
  $query = array(
    'sort' => 'name',
    'limit' => 5,
    'name' => $string,
    'appMetadata.hid.login' => 'true'
  );
  $variables['headers'] = array(
    'Authorization' => 'Bearer '.variable_get('hid2_contact_ref_v2_api_key', NULL)
  );
  $url = variable_get('hid2_contact_ref_api_endpoint', 'https://api.humanitarian.id').'/api/v2/user';
  $url .= '?' . http_build_query($query);
  $response = drupal_http_request($url, $variables);
  if ($response->code == '200') {
    $contacts = json_decode($response->data);
    $out = [];
    foreach ($contacts as $contact) {
      $out["$contact->name [id: $contact->id]"] = $contact->name;
    }
    drupal_json_output($out);
  }

  drupal_exit();
}

function hid2_contact_ref_get_contact($id) {
  $url = variable_get('hid2_contact_ref_api_endpoint', 'https://api.humanitarian.id').'/api/v2/user/'.$id;
  $variables['headers'] = array(
    'Authorization' => 'Bearer '.variable_get('hid2_contact_ref_v2_api_key', NULL)
  );

  $response = drupal_http_request($url, $variables);
  if ($response->code == '200') {
    $contacts = json_decode($response->data);
    $out = [];
    foreach ($contacts as $contact) {
      $out["$contact->name [id: $contact->id]"] = $contact->name;
    }
    drupal_json_output($out);
  }

  drupal_exit();
}

/**
 * Implements hook_theme().
 */
function hid2_contact_ref_theme() {
  return array(
    'hid2_contact_ref_single_contact' => array(
      'variables' => array(
        'contact' => array(),
        'url' => '',
      ),
      'template' => 'templates/hid2-contact-ref-single-contact',
    ),
  );
}
